package dev.abelab.gifttree.db.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class UserGift {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_gift.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_gift.gift_id
     *
     * @mbg.generated
     */
    private Integer giftId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_gift.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_gift.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_gift.received_at
     *
     * @mbg.generated
     */
    private Date receivedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_gift.received_by
     *
     * @mbg.generated
     */
    private Integer receivedBy;
}