version: "3"
services:
  db-local:
    build: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: "gifttree"
      MYSQL_USER: "gifttree"
      MYSQL_PASSWORD: "gifttree"
      MYSQL_ROOT_PASSWORD: "gifttree"
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/log/local:/var/log/mysql
      - ./mysql/db:/var/lib/mysql
  db-test:
    build: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: "gifttree"
      MYSQL_USER: "gifttree"
      MYSQL_PASSWORD: "gifttree"
      MYSQL_ROOT_PASSWORD: "gifttree"
      TZ: "Asia/Tokyo"
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/log/local:/var/log/mysql
