spring:
  datasource:
    url:
    username:
    password:
    driver:
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
    outOfOrder: false
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver: ${spring.datasource.driver}
    locations: classpath:db/migration
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    dateFormat: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Tokyo

server:
  port: 8080

project:
  name: gifttree
  version: 1.0
  package: dev.abelab.gifttree
  mybatis:
    config:
      file: generatorConfig.xml
    model:
      package: db.entity
    client:
      package: db.mapper.base
      type: XMLMAPPER
    map:
      package: db.mapper.base
  swagger:
    protocol: http
    hostname: localhost:${server.port}

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapperLocations:
    - classpath:/db/mapper/base/*Mapper.xml
    - classpath:/db/mapper/*Mapper.xml

gcp:
  project-id:
  credentials_path:
  cloud-storage:
    enabled: false
    bucket-name:

jwt:
  secret: 8WRnDG5cUpi0qD5Kpd3Bx/n+1X6DG7mhQwsCQAVjJLo=
  issuer: gifttree.abelab.dev
  expired_in: 604800 # [秒]

logging:
  level:
    root: INFO
