spring:
  datasource:
    url: jdbc:mysql://localhost:3307/gifttree?useSSL=false&allowPublicKeyRetrieval=true
    username: gifttree
    password: gifttree
    driver: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: ERROR
