package dev.abelab.gifttree.db.mapper.base;

import dev.abelab.gifttree.db.entity.Gift;
import dev.abelab.gifttree.db.entity.GiftExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface GiftBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    long countByExample(GiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int deleteByExample(GiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int insert(Gift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int insertSelective(Gift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    List<Gift> selectByExampleWithBLOBs(GiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    List<Gift> selectByExample(GiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    Gift selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Gift record, @Param("example") GiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Gift record, @Param("example") GiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Gift record, @Param("example") GiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Gift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Gift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gift
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Gift record);
}